### ISSUE TITLE
BlueException 在日志记录丢失错误信息

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/blueapps#3]
https://github.com/TencentBlueKing/blueapps/blob/master/blueapps/core/exceptions/base.py#L35

应该:

```
super(BlueException, self).__init__(message, data, *args)
```

或者提供

```
def __str__(self):
```

非正确实现自定义异常, 带来问题, 如果logger.exception或者 logger.error(e), 是无法看到错误信息的, 只有对应Exception类的类型

**Comment by normal-wls** [comment]
https://pypi.org/project/blueapps/4.1.0/ 
感谢，对应4.1.0版本已修复
